name: Print Env

on:
  workflow_dispatch:
  push:

jobs:
  PrintEnv:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, self-hosted]
    runs-on: ${{ matrix.os }}
    steps:

    - name: Print Env Variables
      shell: pwsh
      run: | 
        dir env: 
