name: Print Env

on:
  workflow_dispatch:
  push:

jobs:
  PrintEnv:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, self-hosted]
    runs-on: ${{ matrix.os }}
    steps:

    - name: Print Env Variables
      shell: pwsh
      run: | 
        dir env: 

    - name: Print PS Module Paths
      shell: pwsh
      run: | 
        $modulePaths = $env:PSModulePath -split [IO.Path]::PathSeparator 
        Write-Host "---- PSModulePath ----"
        $modulePaths | foreach {Write-Host $_}
        Write-Host "---- List modules ----"
        Get-Module -ListAvailable | select Name, Version, Path
