name: Print Env

on:
  workflow_dispatch:
  push:

jobs:
  PrintEnv:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, self-hosted]
    runs-on: ${{ matrix.os }}
    steps:

    - name: Print Env Variables
      shell: pwsh
      run: | 
        dir env: 

    - name: Print PS Module Paths
      shell: pwsh
      run: | 
        $env:PSModulePath -split [IO.Path]::PathSeparator 

    - name: Print Az Module
      shell: pwsh
      run: | 
        Get-Module -ListAvailable Az | select Name, Version, Path

    - name: List Az Module with Azure PowerShell Action, latest version
      uses: azure/powershell@v1.2.0
      with:
        azPSVersion: "latest"
        inlineScript: |
          '------------------------ PSModulePath -------------------------------'
          $env:PSModulePath -split [IO.Path]::PathSeparator 
          '------------------------ List Az Module -----------------------------'
          Get-Module -ListAvailable Az | select Name, Version, Path

    - name: List Az Module with Azure PowerShell Action, 9.6.0
      uses: azure/powershell@v1.2.0
      with:
        azPSVersion: "9.6.0"
        inlineScript: |
          '------------------------ PSModulePath -------------------------------'
          $env:PSModulePath -split [IO.Path]::PathSeparator 
          '------------------------ List Az Module -----------------------------'
          Get-Module -ListAvailable Az | select Name, Version, Path