name: Print Env

on:
  workflow_dispatch:
  push:

jobs:
  PrintEnv:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, self-hosted]
    runs-on: ${{ matrix.os }}
    steps:

    - name: Print Env Variables
      shell: pwsh
      run: | 
        dir env: 

    - name: Print PS Module Paths
      shell: pwsh
      run: | 
        $env:PSModulePath -split [IO.Path]::PathSeparator 

    - name: Print PS Module Paths
      shell: pwsh
      run: | 
        Get-Module -ListAvailable Az 

    - name: Run Azure PowerShell File
      uses: azure/powershell@v1.2.0
      with:
        azPSVersion: "latest"
        inlineScript: |
          Get-Module -ListAvailable Az

    - name: Run Azure PowerShell File
      uses: azure/powershell@v1.2.0
      with:
        azPSVersion: "9.6.0"
        inlineScript: |
          Get-Module -ListAvailable Az