name: Azure PowerShell Action Demo -- script

on:
  workflow_dispatch:
  push:

jobs:
  RunPSScript:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, self-hosted]
    runs-on: ${{ matrix.os }}
    steps:

    - name: Login Azure with SP
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 

    - name: Run Azure PowerShell latest version
      uses: azure/powershell@v1
      with:
        azPSVersion: "latest"
        inlineScript: | 
          Get-Module -ListAvailable Az
          Get-AzVM | where Name -Like "Yan*"

    - name: Run Azure PowerShell specific version
      uses: azure/powershell@v1     
      with:
        azPSVersion: "10.0.0"
        inlineScript: | 
          Get-Module -ListAvailable Az
          Get-AzVM | where Name -Like "Yan*"
