name: AZPS Service Issue Report Mail

on:
  issue_comment:
    types: [created]

jobs:
  SendIssueReportMail:
    runs-on: ubuntu-latest
    if: github.event.issue.number == 1
    steps:

    - name: Get User Mail
      id: get-comment-user-mail
      env:
        GH_TOKEN: ${{ github.token }}
        commentUser: ${{ github.event.comment.user.login }}
      shell: pwsh
      run: |
        Write-Host "comment user is: " $env:commentUser
        $commentUser = "/users/" + $env:commentUser
        $commentUserMail = (gh api -H "Accept: application/vnd.github+json"  -H "X-GitHub-Api-Version: 2022-11-28" $commentUser | ConvertFrom-Json).email
        Write-Host "comment user mail is: " $commentUserMail
        echo "commentUserMail=$commentUserMail" >> $env:GITHUB_OUTPUT

    - name: checkout current repo
      uses: actions/checkout@v3
      with:
        path: ghaction
    
    - name: checkout azure-powershell repo
      uses: actions/checkout@v3
      with:
        repository: Azure/azure-powershell
        path: azure-powershell

    - name: Generate Issue Report
      shell: pwsh
      run: |
        cd azure-powershell
        ../ghaction/ps/generate_issue_report.ps1
        ls azps_service_issue.html
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Post to Logic App to send the mail
      shell: pwsh
      env: 
        uri: "${{ secrets.mail_uri }}"
        receiver: "${{ steps.get-comment-user-mail.outputs.commentUserMail }}"
      run: |
        $title = "Azure PowerShell Service Issue Report"
  
        cd azure-powershell
        $content=(Get-Content azps_service_issue.html -Raw -Encoding ascii)
  
        $body = @{}
        $body["receiver"] = $env:receiver
        $body["title"]= $title
        $body["content"]= $content
        $body = $body | ConvertTo-Json
  
        Invoke-WebRequest -Method Post -Uri $env:uri -ContentType "application/json" -Body "$body" -Debug -Verbose
