name: AZPS Service Issue Report Mail

on: [push, workflow_dispatch]

jobs:
  SendIssueReportMail:
    runs-on: ubuntu-latest
    steps:

    - name: checkout current repo
      uses: actions/checkout@v3
      with:
        path: ghaction
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: install node modules
      run: |
        npm install nodemailer

    - name: checkout azure-powershell repo
      uses: actions/checkout@v3
      with:
        repository: Azure/azure-powershell
        path: azure-powershell

    - name: Generate Issue Report
      shell: pwsh
      run: |
        cd azure-powershell
        ../ghaction/ps/generate_issue_report.ps1
        ls azps_service_issue.html
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Send Mail
      run: |
        node ./ghaction/js/sendMail.js
      env: 
        mail_sender: ${{ secrets.mail_sender }}
        mail_receiver: ${{ secrets.mail_receiver }}
        mail_pass: ${{ secrets.mail_pass }}
        mail_subject: "Azure PowerShell Service Issue Report"
        mail_body_file: ./azure-powershell/azps_service_issue.html
