name: AZPS Service Issue Report Mail

on:
  issue_comment:
    types: [created]

jobs:
  SendIssueReportMail:
    runs-on: ubuntu-latest
    if: github.event.issue.number == 1
    steps:

    - name: Get User Mail
      id: get-comment-user-mail
      env:
        GH_TOKEN: ${{ github.token }}
        commentUser: ${{ github.event.comment.user.login }}
      shell: pwsh
      run: |
        Write-Host "comment user is: " $env:commentUser
        $commentUser = "/users/" + $env:commentUser
        $commentUserMail = (gh api -H "Accept: application/vnd.github+json"  -H "X-GitHub-Api-Version: 2022-11-28" $commentUser | ConvertFrom-Json).email
        Write-Host "comment user mail is: " $commentUserMail
        echo "commentUserMail=$commentUserMail" >> $env:GITHUB_OUTPUT

    - name: checkout current repo
      uses: actions/checkout@v3
      with:
        path: ghaction
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: install node modules
      run: |
        npm install nodemailer

    - name: checkout azure-powershell repo
      uses: actions/checkout@v3
      with:
        repository: Azure/azure-powershell
        path: azure-powershell

    - name: Generate Issue Report
      shell: pwsh
      run: |
        cd azure-powershell
        ../ghaction/ps/generate_issue_report.ps1
        ls azps_service_issue.html
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Send Mail
      run: |
        node ./ghaction/js/sendMail.js
      env: 
        mail_sender: ${{ secrets.mail_sender }}
        mail_receiver: ${{ steps.get-comment-user-mail.outputs.commentUserMail }}
        mail_pass: ${{ secrets.mail_pass }}
        mail_subject: "Azure PowerShell Service Issue Report"
        mail_body_file: ./azure-powershell/azps_service_issue.html
